### ISSUE TITLE
Changing config display names or value types breaks loading config, causing a crash

### ISSUE THREAD

**Issue by S-B99** [S-B99/kamiblue#213]

**Comment by S-B99** [comment]
So any time you rename or delete the display name for a setting (the one that's saved in the config) or change the value type (eg double to enum) the the config doesn't know how to load it, or what to load so it crashes.

A solution would preferably have it delete the unknown value, if not skipping it, but I have no idea how the config system works so any help from @zeroeightysix would be appreciated

**Comment by zeroeightysix** [comment]
What's the stack trace?

**Comment by S-B99** [comment]
I'll be home in about 10 minutes, but it's usually just caught exception and a bunch of json related stuff

**Comment by S-B99** [comment]
thanks mojang ;p 
![Screenshot_20191203_151921](https://user-images.githubusercontent.com/17222512/70086380-499b6600-15e0-11ea-94a5-f0888e9dbd6d.png)

[test 1](https://hastebin.com/mipetipepe.sql)
cannot reproduce with changing the display name
now trying it with value

**Comment by S-B99** [comment]
[changing value produces this](https://hastebin.com/kurizokitu.sql)

It worked fine going from double to int, this was from int to enum

**Comment by blockparole** [comment]
Right now the problematic exception is `IllegalArgumentException`.
Catching this exception at [L57](https://github.com/S-B99/KAMI/blob/c3410709dc38fb09bb05f4696080fdf81aa36261/src/main/java/me/zeroeightsix/kami/setting/config/Configuration.java#L57) doesnt solve the problem, however, catching like at [L76](https://github.com/S-B99/KAMI/blob/c3410709dc38fb09bb05f4696080fdf81aa36261/src/main/java/me/zeroeightsix/kami/setting/config/Configuration.java#L76) like this however has the wanted effect of not crashing and loading a fresh config:
```private static void loadConfiguration(SettingsRegister register, JsonObject input) {
        for (Map.Entry<String, JsonElement> entry : input.entrySet()) {
            String key = entry.getKey();
            JsonElement element = entry.getValue();
            if (register.registerHashMap.containsKey(key)) {
                loadConfiguration(register.subregister(key), element.getAsJsonObject());
            } else {
                Setting setting = register.getSetting(key);
                if (setting == null) continue;
                try {
                    setting.setValue(setting.converter().reverse().convert(element));
                } catch (Exception e) {
                    KamiMod.LOGGER.error("KAMI Config malformed: resetting.");
                    loadConfiguration(new JsonObject()); // Just reset it!
                }
            }
        }
    }```

Dont have more time right now so im just posting this stuff up there kinda raw.

Btw. it would be awesome if we could just reset the broken node instead of the whole config :3

**Comment by S-B99** [comment]
Yep, I will implement this for now but I would love to just delete that section if I knew how it does that

**Comment by blockparole** [comment]
no dont use this, its not really sane. i just used this for testing

**Comment by S-B99** [comment]
I'm wondering if there would be a way to warn the user on startup their config was reset, only once

**Comment by S-B99** [comment]
Ah, alright. I'll rewrite it then

**Comment by S-B99** [comment]
Another example stack trace for [reference](https://pastebin.com/raw/e84F0dxk)

And [another](https://pastebin.com/raw/i1cJSCh4)
