### ISSUE TITLE
Offhand Gap (Toggle gap with key or right clicking mouse)

### ISSUE THREAD

**Issue by S-B99** [S-B99/kamiblue#356]
Replaces your totem with a _gapple_ while holding right click

**Comment by m-ryals** [comment]
i think that since ppl ofthen hold rightclick while crystalling that it should be a key that you press that both puts a gap in your offhand and overrides autototem. or maybe work like the preview mod, where the code is in autototem and the module itself only serves as a way to bind it. also maybe a setting to disable it under a certain health? i dont know. just a suggestion!

**Comment by S-B99** [comment]
The autototem code is in autototem?

**Comment by m-ryals** [comment]
i mean like integrate offhandgap into autototem
so the two dont conflict

**Comment by S-B99** [comment]
Oh. That's the point, it disables autototem when holding right click

**Comment by m-ryals** [comment]
k that makes a bit more sense

**Comment by m-ryals** [comment]
i just had an idea, maybe make this into a smart offhand module, where you can switch to xp or gapples based on user-defined health settings? and also based on what the user is holding, so they wont accidentally switch when holding a bow for example

**Comment by S-B99** [comment]
Why tho
