### ISSUE TITLE
wassup

### ISSUE THREAD

**Issue by r33666** [S-B99/kamiblue#558]
yo wassup homie

a good idea in my opinion, a real enhancement, a beneficial move in the right direction would be to delete your moronic, dim-witted client. I would debate with you why this thing is pure hot trash but I don't engage in battles of wits with unarmed opponents. 🔫 🤠 

>When I find myself in times of trouble
Mother Mary comes to me
Speaking words of wisdom, let it be.
And in my hour of darkness
She is standing right in front of me
Speaking words of wisdom, let it be.
Let it be, let it be.
Whisper words of wisdom, let it be

**Comment by S-B99** [comment]
Why?

Provide an argument at the very least.

**Comment by r33666** [comment]
how do you dev when you cant even read smh. I think being illiterate is reason enough to delete maybe get Grammarly premium or some shit idk

> I would debate with you why this thing is pure hot trash but I don't engage in battles of wits with unarmed opponents. 🔫 🤠

**Comment by Vonr** [comment]
hey assumedly educated person, i hope that you know that even though bella may not be the best dev, she will always be better than you at everything she does. you are worthless in this world. more worthless than trash on a street. more worthless than the people you claim to be lowlife scum. they are infinitely more beautiful than you ever will be. and remember that just because your mother says she loves you doesn't mean anyone else even remotely likes you or should have to deal with your moronic bullcrap.

**Comment by S-B99** [comment]
3/10 shitty troll

not even self aware

if you provide a real argument I'd consider it.

**Comment by S-B99** [comment]
If you have to ask someone to delete something instead of letting it die, then maybe it isn't "hot trash", as you described it?
